% Analyze the optimized kappa_star values across stored Givens solutions.

activate

% Load the stored solutions for the selected dimension.
K = 5;
plotDir = fullfile('plots', sprintf('K=%d', K));
load(fullfile(plotDir, sprintf('haar_givens_K%d_solutions.mat', K)))

N = numel(solutions);
kappas = cellfun(@(s) s.kappa_star, solutions);
eigenvalues_Q = complex(zeros(N, K));

% Tolerance for grouping numerically equal objective values.
tol = 1e-8;
kappas_round = round(kappas/tol)*tol;

for i = 1:N
    eigenvalues_Q(i,:) = eig(solutions{i}.Q_star).';
end

eigenvalue_moduli = abs(eigenvalues_Q);
eigenvalue_angles = angle(eigenvalues_Q);

[unique_kappas, ~, idx_kappa_group] = unique(kappas_round);
kappa_counts = accumarray(idx_kappa_group, 1);
nGroups = numel(unique_kappas);

fprintf('\nkappa_star analysis\n')
fprintf('K: %d\n', K)
fprintf('Total solutions: %d\n', N)
fprintf('Tolerance: %.1e\n', tol)
fprintf('min(kappa_star): %.15g\n', min(kappas))
fprintf('max(kappa_star): %.15g\n', max(kappas))
fprintf('range: %.3e\n', max(kappas)-min(kappas))
fprintf('mean(kappa_star): %.15g\n', mean(kappas))
fprintf('std(kappa_star): %.3e\n', std(kappas))
fprintf('Unique kappa groups: %d\n', nGroups)
fprintf('max |abs(eig(Q_star))-1|: %.3e\n', ...
    max(abs(eigenvalue_moduli(:)-1)))

kappa_table = table((1:nGroups).', unique_kappas, kappa_counts, ...
    'VariableNames', {'Group', 'KappaBest', 'Count'});

disp(kappa_table)

solution_id = repelem((1:N).', K);
eigenvalue_id = repmat((1:K).', N, 1);
eigenvalue_real = real(eigenvalues_Q(:));
eigenvalue_imag = imag(eigenvalues_Q(:));
eigenvalue_modulus = eigenvalue_moduli(:);
eigenvalue_angle = eigenvalue_angles(:);

eigenvalue_table = table( ...
    solution_id, ...
    eigenvalue_id, ...
    eigenvalue_real, ...
    eigenvalue_imag, ...
    eigenvalue_modulus, ...
    eigenvalue_angle, ...
    'VariableNames', { ...
    'Solution', ...
    'Eigenvalue', ...
    'Real', ...
    'Imag', ...
    'Modulus', ...
    'Angle'});

save(fullfile(plotDir, 'kappa_star_analysis.mat'), ...
    'K', ...
    'kappas', ...
    'tol', ...
    'kappas_round', ...
    'unique_kappas', ...
    'idx_kappa_group', ...
    'kappa_counts', ...
    'kappa_table', ...
    'eigenvalues_Q', ...
    'eigenvalue_moduli', ...
    'eigenvalue_angles', ...
    'eigenvalue_table')

writetable(kappa_table, fullfile(plotDir, 'kappa_star_analysis.csv'))
writetable(eigenvalue_table, fullfile(plotDir, 'Q_star_eigenvalues.csv'))
